export const data = [
  {
    breeds: [],
    categories: [{ id: 7, name: "ties" }],
    id: "t6",
    url: "https://cdn2.thecatapi.com/images/t6.gif",
    width: 968,
    height: 1296,
  },
  {
    breeds: [],
    categories: [{ id: 7, name: "ties" }],
    id: "tu",
    url: "https://cdn2.thecatapi.com/images/tu.jpg",
    width: 2304,
    height: 3072,
  },
  {
    breeds: [],
    categories: [{ id: 7, name: "ties" }],
    id: "u1",
    url: "https://cdn2.thecatapi.com/images/u1.jpg",
    width: 625,
    height: 446,
  },
  {
    breeds: [],
    categories: [{ id: 7, name: "ties" }],
    id: "10j",
    url: "https://cdn2.thecatapi.com/images/10j.jpg",
    width: 500,
    height: 335,
  },
  {
    breeds: [],
    categories: [{ id: 7, name: "ties" }],
    id: "10m",
    url: "https://cdn2.thecatapi.com/images/10m.jpg",
    width: 600,
    height: 393,
  },
  {
    breeds: [],
    categories: [{ id: 7, name: "ties" }],
    id: "114",
    url: "https://cdn2.thecatapi.com/images/114.jpg",
    width: 1280,
    height: 850,
  },
  {
    breeds: [],
    categories: [{ id: 7, name: "ties" }],
    id: "11g",
    url: "https://cdn2.thecatapi.com/images/11g.jpg",
    width: 500,
    height: 193,
  },
  {
    breeds: [],
    categories: [{ id: 7, name: "ties" }],
    id: "12a",
    url: "https://cdn2.thecatapi.com/images/12a.jpg",
    width: 604,
    height: 453,
  },
  {
    breeds: [],
    categories: [{ id: 7, name: "ties" }],
    id: "12j",
    url: "https://cdn2.thecatapi.com/images/12j.jpg",
    width: 384,
    height: 482,
  },
  {
    breeds: [],
    categories: [{ id: 7, name: "ties" }],
    id: "3to",
    url: "https://cdn2.thecatapi.com/images/3to.jpg",
    width: 500,
    height: 378,
  },
];
