export const REQUEST_CATEGORY_ITEM_START = 'REQUEST_CATEGORY_ITEM_START';
export const REQUEST_CATEGORY_ITEM_SUCCESS = 'REQUEST_CATEGORY_ITEM_SUCCESS';
export const REQUEST_CATEGORY_ITEM_FAILED = 'REQUEST_CATEGORY_ITEM_FAILED';
export const SELECTED_CATEGORY = 'SELECTED_CATEGORY';
export const LIMIT_HANDLER = 'LIMIT_HANDLER';
